gdb: generic-hack: testsuite gdb.base/bt-on-fatal-signal.exp
FAIL: gdb.base/bt-on-fatal-signal.exp: SEGV: $saw_fatal_msg
FAIL: gdb.base/bt-on-fatal-signal.exp: SEGV: $saw_bt_start

FAIL case
Fatal signal:

exp:
Fatal signal: Segmentation fault

root cause: strsignal marked
2022-06-30 17:34 Penny Chen  gdb: generic-hack: Fix cygwin build error
error: 'strsignal' was not declared in this scope

event-top.c:892:
if (bt_on_fatal_signal)
    {
		      sig_write ("\n\n");
					sig_write (_("Fatal signal: "));
					sig_write (strsignal (sig));